CREATE TABLE IF NOT EXISTS users(
	id UUID PRIMARY KEY DEFAULT uuidv7(),
	username VARCHAR(50) UNIQUE NOT NULL,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


