spring.application.name=jobcubator

# Postgresql database connection
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Standard JPA/Hibernate properties
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT secret key (with default for development)
jwt.secret.key=${JWT_SECRET_KEY}
server.address=0.0.0.0

app.s3.endpoint=${SPRING_AWS_S3_ENDPOINT}
app.s3.access-key=${SPRING_AWS_S3_ACCESS_KEY}
app.s3.secret-key=${SPRING_AWS_S3_SECRET_KEY}
app.s3.bucket-name=user-files
app.s3.region=us-east-1