spring.application.name=jobcubator

# Postgresql database connection
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Standard JPA/Hibernate properties
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT secret key (with default for development)
jwt.secret.key=${JWT_SECRET_KEY}
server.address=0.0.0.0

app.s3.endpoint=${SPRING_AWS_S3_ENDPOINT}
app.s3.access-key=${SPRING_AWS_S3_ACCESS_KEY}
app.s3.secret-key=${SPRING_AWS_S3_SECRET_KEY}
app.s3.bucket-name=user-files
app.s3.region=us-east-1
app.s3.public-endpoint=http://localhost:9000

# File size limitation.
spring.servlet.multipart.max-request-size=10MB

# Chat Settings
ai-service.url=http://localhost:3000

## Redis Configuration
#spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
#spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
#spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:}
#spring.data.redis.timeout=60000
#spring.data.redis.database=0
#
## Redis Connection Pool (Lettuce)
#spring.data.redis.lettuce.pool.max-active=8
#spring.data.redis.lettuce.pool.max-idle=8
#spring.data.redis.lettuce.pool.min-idle=0
#spring.data.redis.lettuce.pool.max-wait=-1ms
#
## Cache Configuration
#spring.cache.type=redis
#spring.cache.redis.time-to-live=3600000
#spring.cache.redis.cache-null-values=false
#spring.cache.redis.key-prefix=jobcubator:
#spring.cache.redis.use-key-prefix=true